---
driver_plugin: vagrant
platforms:
- name: ubuntu-14.04
  driver_config:
    require_chef_omnibus: '11.14'
    box: ubuntu1404
- name: ubuntu-12.04
  driver_config:
    require_chef_omnibus: '11.14'
    box: ubuntu1204
- name: centos-7.0
  driver_config:
    require_chef_omnibus: '11.14'
    box: centos70
- name: centos-6.4
  driver_config:
    require_chef_omnibus: '11.14'
    box: centos64
- name: centos-5.11
  driver_config:
    require_chef_omnibus: '11.14'
    box: centos511
- name: windows-2012r2
  driver_config:
    require_chef_omnibus: '11.14'
    box: windows-2012r2
  attributes:
    omnibus_updater:
    version: 12.5.1
suites:
- name: default
  run_list:
  - recipe[omnibus_updater_test::default]
  #- recipe[minitest-handler]
- name: upgrade
  run_list:
  - recipe[omnibus_updater_test::version_upgrade]
  #- recipe[minitest-handler]
