driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  driver_config:
    require_chef_omnibus: '11.14'
- name: ubuntu-12.04
  driver_config:
    require_chef_omnibus: '11.14'
- name: centos-7.0
  driver_config:
    require_chef_omnibus: '11.14'
- name: centos-6.4
  driver_config:
    require_chef_omnibus: '11.14'
- name: centos-5.11
  driver_config:
    require_chef_omnibus: '11.14'
- name: windows-2012r2-chef12
  driver_config:
  box: chef/windows-server-2012r2-standard

suites:
- name: default
  run_list:
  - recipe[test::default]
- name: upgrade
  run_list:
  - recipe[test::version_upgrade]
