driver:
  name: vagrant
  require_chef_omnibus: '11.14'

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
  - name: debian-8.4
  - name: fedora-23
  - name: opensuse-13.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2012r2-chef12
    driver:
      box: chef/windows-server-2012r2-standard

suites:
- name: rubygem_to_omnibus
  run_list:
  - recipe[test::default]
- name: upgrade
  run_list:
  - recipe[test::version_upgrade]
